### ISSUE TITLE
How to get the OLN objectness ranking for the COCO voc->nonvoc experiment?

### ISSUE THREAD

**Issue by andrehuang** [facebookresearch/Generic-Grouping#11]
Dear authors,

Maybe I missed it in the paper, but can you clarify again how do you generate the OLN objectness ranking score for the GGN in Table 6? 
Since OLN objectness is a learned score, I think you should have trained a separate OLN model? Is it trained on COCO images directly, or trained on the pairwise affinity maps?

<img width="490" alt="image" src="https://user-images.githubusercontent.com/25845602/185205317-d03577f5-1583-467a-968a-e534b7b71f16.png">

Best,
Haiwen

**Comment by weiyaowang** [comment]
Sorry for the late reply!
We use the pre-trained OLN model on VOC classes. The method is documented here: https://github.com/facebookresearch/Generic-Grouping/blob/main/pa_lib/oln_ranker.py

Basically we find the proposal similar to a Pseudo-GT from PA, and compute its objectness from OLN's RPN and RoI branch.
