### ISSUE TITLE
How to evaluate the LVIS coco->non-coco setting?

### ISSUE THREAD

**Issue by wjn922** [facebookresearch/Generic-Grouping#4]
Hi, 

Thanks for your wonderful work. Could you please give some instructions on how to evaluate the LVIS coco->non-coco setting in this repo?

**Comment by wjn922** [comment]
Then does it mean that if I use the pre-processed json files, I can use the standard coco evaluation api to do the evaluation?

**Comment by weiyaowang** [comment]
Yes; I think that's the correct understanding. Just replacing it with the pre-processed json files. Double check the img_prefix (depending on how you stored the data).

**Comment by wjn922** [comment]
Thanks.
