### ISSUE TITLE
Results of box result

### ISSUE THREAD

**Issue by wangchust** [facebookresearch/Generic-Grouping#5]
Could you provide AR results of boxes under COCO to UVO setting?

**Comment by wangchust** [comment]
> Thanks for your interests! I will add a box eval on Mask R-CNN in UVO setting. Or do you prefer Faster R-CNN results on UVO setting?

That would be better! Thank you for your kindness

**Comment by wangchust** [comment]
Any update on box results?

**Comment by weiyaowang** [comment]
Apology for the delay! Here's the box result for Faster R-CNN:

> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.240
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.414
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.243
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.298
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 30 ] = 0.422
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 50 ] = 0.468
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.522
 
Please let me know if you have more questions on this.
