### ISSUE TITLE
GGN-OLN Checkpoint is missing

### ISSUE THREAD

**Issue by curiosity654** [facebookresearch/Generic-Grouping#9]
In the second row of the model zoo table, the link "[GGN-OLN](https://github.com/facebookresearch/Generic-Grouping/blob/main)" is missing. Could you please update the link?
By the way, does the "GGN-OLN" means OLN architecture trained with pseudo label and corresponds to the following result in the paper?
![image](https://user-images.githubusercontent.com/34833233/174508685-78d58c1f-3cdc-4a57-8af5-daef2a9edde3.png)

**Comment by weiyaowang** [comment]
Thanks for identifying this! It has been added to the README model zoo.
